### ISSUE TITLE
汉化失败！

### ISSUE THREAD

**Issue by am-abudu** [asdjgfr/clash-windows-sinicization#1]
正在解压...
完成！

汉化失败，错误：
Error: EPERM: operation not permitted, mkdir 'D:\Program Files\Clash for Windows\resources\clash-windows-sinicization\tmp'

**Comment by am-abudu** [comment]
以管理员权限运行后解决。。

**Comment by am-abudu** [comment]
似乎汉化成功后客户端并没有变化，版本0.14.1

**Comment by asdjgfr** [comment]
解包后发现原作者加密混淆了源码，解析成本太高，所以在原作者提供i18n之前不会再更新了
